name: database-test

on:
  pull_request: ~

jobs:
  database-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/bake-action@v6
        with:
          pull: true
          load: true
          files: |
            docker-compose.yaml
          set: |
            setup.tags=setup
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/develop
            *.cache-to=type=gha,scope=${{github.ref}},mode=max

      - run: docker compose up database -d
      - run: docker compose run -T setup
      - run: docker compose run -T setup composer load-db